### ISSUE TITLE
rebuilding?

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#110] opened 2022-04-27 12:56 UTC
MFC seems to "rebuild" when it doesn't need to. For example, from the master branch, when one builds the pre_process and simulation codes then runs `make test` we get 

```
sbryngelson@batch3 proj/mfc-develop $ ./mfc.sh test

     ___            ___          ___
    /__/\          /  /\        /  /\
   |  |::\        /  /:/_      /  /:/
   |  |:|:\      /  /:/ /\    /  /:/
 __|__|:|\:\    /  /:/ /:/   /  /:/  ___
/__/::::| \:\  /__/:/ /:/   /__/:/  /  /\
\  \:\~~\__\/  \  \:\/:/    \  \:\ /  /:/
 \  \:\         \  \::/      \  \:\  /:/
  \  \:\         \  \:\       \  \:\/:/
   \  \:\         \  \:\       \  \::/
    \__\/          \__\/        \__\/

Check Environment:
> Found 7/7 Command-line utilities ✓
> NVHPC (NVFortran) v21.9-0 >= v21.7.0 ✓
Test:
> pre_process needs (re)building...
> Package pre_process
> > Building... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
> > Updating lock file...
> Package pre_process - Built ✓
> simulation needs (re)building...
> Package simulation requires fftw3.
> > Package fftw3 - satisfied ✓
> Package simulation
> > Building... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
```

**Comment by henryleberre** [comment] 2022-05-05 18:57
[run.py](https://github.com/MFlowCode/MFC-develop/blob/GPU/bootstrap/internal/run.py) and [test.py](https://github.com/MFlowCode/MFC-develop/blob/GPU/bootstrap/internal/test.py) were using [build.py](https://github.com/MFlowCode/MFC-develop/blob/GPU/bootstrap/internal/build.py)'s `is_build_satisfied` method to check whether the targets they were asked to use were built. Since it was designed for (https://github.com/MFlowCode/MFC-develop/blob/GPU/bootstrap/internal/build.py), it checked whether a target was cleaned or not, since we suspect that users who run `./mfc.sh clean`, and then run `./mfc.sh build ...` wish to rebuild the targets they have cleaned if they select them. This change made `is_build_satisfied` a slight misnomer.

Since that function was rather complex, having to recursively check for build completion (without running into infinite loops), checking when files were last modified and comparing that with binaries, checking for entries in the lock file, and so on, I renamed it to `check_build_status` with an new parameter `bIgnoreCleans`. 

From there, I created two functions which are used instead, and serve as straightforward wrappers around `check_build_status`:
```python
def is_built(self, name: str):
    return self.check_build_status(name, bIgnoreCleans=True)

def build_should_rebuild(self, name: str):
    return not self.check_build_status(name, bIgnoreCleans=False)
```

These changes have been pushed to the development repository located at ORNL (https://code.ornl.gov/ecpcitest/cfd154/MFC-develop). They will (soon) be merged here. The commit is available [here](https://code.ornl.gov/ecpcitest/cfd154/MFC-develop/-/commit/38d8db1388ba3cfc6e7a9c925acd0b6aa2d0ad0a).

**Comment by sbryngelson** [comment] 2022-05-05 19:01
The best way to check if a code needs to be recompiled is to do it in the GNU Make way... we should use existing tools when they are available, and `make` is available everywhere. Is there a reason we don't do this?

**Comment by henryleberre** [comment] 2022-05-05 19:18
Yes, both fortunately and unfortunately that are reasons we need these functions. For instance, we have to clone our dependencies, and we couldn't check whether they were actually built using make, since it would be in empty directory, and just fail. We also have to check whether we updated a dependency (such as changing its version/git repository commit hash) and such. Checking whether we cleaned a target is extremely simple since we set a flag in the lock file. One example of why it's easier to do it this way, is that a lot of our build commands run `./configure` and it would take a lot of time to reach `make`. I believe that engineering around that would be more troublesome than this approach. But it also has the advantage of printing that we are building a target when we aren't.

**Comment by sbryngelson** [comment] 2022-05-05 20:08
I meant just using make for the actual fortran source code, not the dependencies.

**Comment by henryleberre** [comment] 2022-05-05 20:25
That actually isn't possible since we copy over the source files to build/<configuration name>/src/<target name> and it changes their last modification date with `make`. There is maybe a workaround, and I've tried some before but I always had issues with it. That would also make us have to support two types of `cleaning`.

**Comment by sbryngelson** [comment] 2022-05-05 20:27
Ok. I will close the issue with the pull request.

**Closed** 2022-05-21 12:23 UTC
Labels: bug
